// Generated by CoffeeScript 1.3.3

define("botton/1.0.0/button-debug", ["$-debug", "gallery/jquery-ui/1.9.1/jquery-ui-debug"], function(require, exports, module) {
  var $;
  $ = require('$-debug');
  require('gallery/jquery-ui/1.9.1/jquery-ui-debug');
  return $('#box').button();
});
